version: 0.1
log:
  fields:
    service: registry
    environment: develop
storage:
    qiniu:
        accesskey: xxxx
        secretkey: xxx
        bucket: registry
        domain: 7xo9fd.com0.z0.glb.clouddn.com
        useruid: 1380448066
        adminak: xxx
        adminsk: xxx
        refreshcacheurl: http://apihub-z0.qbox.me/mc/del
    cache:
        blobdescriptor: inmemory
    redirect:
        disable: true
http:
    addr: :5000
    secret: asecretforlocaldevelopment
    headers:
        X-Content-Type-Options: [nosniff]
