version: 0.1
log:
  fields:
    service: registry
    environment: develop
storage:
    qiniu:
        accesskey: xxxx
        secretKey: xxx
        bucket: registry
        domain: 7xo9fd.com0.z0.glb.clouddn.com
    cache:
        blobdescriptor: inmemory
    redirect:
        disable: true
http:
    addr: :5000
    secret: asecretforlocaldevelopment
    headers:
        X-Content-Type-Options: [nosniff]
